### ISSUE TITLE
All tests are passing without any changes to code 

### ISSUE THREAD

**Issue by jessicasalmon** [foundersandcoders/ws-password-management#14]
Hey @jsms90 @ronanyeah

There's a slightly significant issue here in that all tests are passing, before any code has been written. 

I just pulled the repo down and ran npm test, and all three tests passed.

**Comment by eliasmalik** [comment]
I think this is because in `jest`, tests that finish without assertions are considered to have passed. For example, this passes:
```js
test('test', () => {});
```

As soon as they add any code that executes the callback, their test will fail. I don't know `jest` at all, so don't know if we can change this behaviour. Would be easy to switch to `tape` though.
