### ISSUE TITLE
Use of promises 

### ISSUE THREAD

**Issue by jessicasalmon** [foundersandcoders/ws-password-management#2]
Thanks for putting this workshop together - I really enjoyed the readme (esp the hashing options) and it seems clear and a digestible 🎉  

My first thoughts are, should we use callbacks in this exercise instead of promises? I don't think they'll have done promises yet and it'd be a shame if they spent the workshop figuring out promises for the first time instead of engaging with the material. Let me know your thoughts @ronanyeah @alexis-l8 @jsms90 @des-des

oh and @jsms90 please correct me if I'm wrong about them not having done promises yet :)

**Comment by ronanyeah** [comment]
The exercise supports both, the choice is there. (And really they should know promises 7 weeks into JS course.)

**Comment by jsms90** [comment]
My stance has not changed since [the last time we discussed the introduction of promises to the course](https://github.com/foundersandcoders/master-reference/issues/262#issuecomment-301845918).
+ Focusing on the fundamentals is of greater benefit to students in the long run. It sets them up to make better judgement calls for themselves in future.
+ If you understand callbacks, promises are no problem. The same is not true the other way around.
+ Plenty of 3rd party APIs use a callback pattern. Even if more and more node code is using promises, we are not doing students any favours if we let them leave the course without fully understanding callbacks.

Having promises in the course would be great. But not at the expenses of _fully_ understanding callbacks. The current level of understanding is not completely solid yet. It's better for the students to spend more time getting comfortable with callbacks, than moving on before having deeply absorbed the fundamentals.

The most successful workshops (and the most successful weeks) are those which are designed with the learning outcomes in mind.

If students are busy trying to wrap their heads around promises, that's energy they could be spending on wrapping their heads around authentication. When too many new concepts are thrown into the mix at once, students end up thinking the two struggles are somehow related e.g. authentication has to be done with promises.

**Comment by ronanyeah** [comment]
@jsms90 Honestly, when I wrote this workshop I thought promises were going to be in Week 4 or something. I thought I was being nice by even giving callbacks as an option!! I certainly wouldn't want them to be learning auth and promises in the same week. Anyway, I'll make callbacks the default, but probably not for a few days.

**Comment by jsms90** [comment]
@ronanyeah Ahhh I see. Yeah makes perfect sense.

I wrote it in callbacks when I was user testing the workshop. I'll push up what I've done to go in a `solution` folder (to satisfy issue #3 ). If you guys have a look at that and whether I've understood correctly, we might be able to use that.
